### ISSUE TITLE
Tutorial: How to build an application with IPFS PubSub Room

### ISSUE THREAD

**Issue by daviddias** [libp2p/research-pubsub#18]
📣 @pgte just launched a new Tutorial that shows how to use PubSub in [ipfs-pubsub-room](https://github.com/ipfs-labs/ipfs-pubsub-room) 🎉

[![image](https://user-images.githubusercontent.com/1211152/28114238-e540840e-66f7-11e7-952c-1ebbc211ac30.png)](https://www.youtube.com/watch?v=Nv_Teb--1zg)

Watch the video here https://www.youtube.com/watch?v=Nv_Teb--1zg. Awesome work @pgte! I had a blast watching the tutorial! Lots of content packed in a short and well-paced video 👏🏽👏🏽👏🏽👏🏽👏🏽👏🏽

Everyone is welcome to post feedback and questions

**Comment by agahEbrahimi** [comment]
Hello @diasdavid 
I watched the video and followed the instructions step by step and even copied in the code from the repo, but the clients don't recognize the other peers joining the room. 
It initializes the IPFS node correctly and gives me `IPFS node ready with address QmXngKRqUJJpdz4fpi6aUCxqtofaTXGL4xbT9Hstc1V4pJ` as a message but nothing afterwards.

**Comment by pgte** [comment]
@agahEbrahimi @Juanperezc updated dependencies: https://github.com/ipfs-shipyard/ipfs-pubsub-room-demo/commit/93188cc81bf64c3877f74c933fe887aab0d38643

After updating dependencies, I recompiled the app and tried it, and everything seams to be running ok.
Please tell me if this doesn't work for you.
Thank you!
