### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by daviddias** [libp2p/research-pubsub#5]
It would be good to keep a glossary close of all the terms we might use during the discussions, to make sure that there are no misinterpretations, specially in a discussion that involves so many people from different groups with different backgrounds.

Example: Authenticated vs Certified https://github.com/ipfs/notes/issues/154

We can start by adding descriptions to this issue and them compile a markdown file, sounds good? Thoughts? @RichardLitt you probably have a very good suggestion on how to do this that makes it easy searchable and reference'able.

**Comment by RichardLitt** [comment]
I think this is a good idea. 

I think that these should go into the existing glossary, at ipfs/glossary. I think we can work on search and reference-able when ctrl+f breaks down; this won't happen for a few hundred entries, though. 

How does it sound, putting things in there?

**Comment by diasdavid** [comment]
@RichardLitt sounds good to me :)

**Comment by RichardLitt** [comment]
This should be closed after there is a note added to the README in this repository about the glossary and other relevant repositories for pubsub.

**Comment by diasdavid** [comment]
Apparently, this is not the first time this idea comes around:

- https://github.com/ipfs/notes/issues/38
- https://github.com/ipfs/notes/issues/7

**Comment by RichardLitt** [comment]
Closed those and added their content to the repository.
