### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by daviddias** [libp2p/research-pubsub#6]
This first major and important step towards PubSub is to list out and nail what are going to be the use cases, so that we can extract in advance what are the requirements and desired interfaces. It shouldn't be the same person writing all of them.

We kicked off this list at the IPFS Workshop, but the ones present need to be completed. Document can be found here:

https://github.com/libp2p/pubsub/blob/master/USECASES.md

**Goal**
- [ ] Have at least 15 or more use cases written by 10 or more people until next discussion

**Comment by sixcorners** [comment]
Can random people add to the list? Is this a list of well thought out and agreed upon use cases or can people suggest anything? If I wanted to try to submit a use case should I reply here as a comment, add an issue here: https://github.com/ipfs/notes/labels/pubsub, or should I submit pull requests or something else?
